### PR TITLE
Allow hyphenated HTML attributes

### PR DESCRIPTION
**Pull request by SimonJF**
Modern HTML allows hyphens in attributes. Take this Bootstrap code:

```
      <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbars" aria-controls="navbars"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
```

This small patch allows hyphenated attributes in Links.

### CODE REVIEW

**Comment by jamescheney** [comment]
What about `xmlParser`/`xmlLexer`?  Do they have the same problem?

**Comment by SimonJF** [comment]
Yep, `xmlLexer` does (having never had to touch `xmlLexer`, I missed this one). Should be fixed in latest commit.

**Comment by jamescheney** [comment]
Cool. As per #518 I kind of think we should turn things like `xmlLexer`/`xmlParser` into Links code eventually (if there are any volunteers to port ocamllex/ocamlyacc to Links... :cricket: :cricket:)

**Comment by SimonJF** [comment]
I was _very_ confused by that comment until I saw that `:cricket:` rendered as the insect in Slack :)

**Comment by jamescheney** [comment]
Yeah, my browser doesn't render it correctly in Github either.

**Pull request merged**
