### PR TITLE
Constrain Postgres bindings to 4.0.1.

### PR DESCRIPTION
**Pull request by SimonJF**
It's not playing nicely with 4.1 at the moment, so constraining for now.

### CODE REVIEW

**Comment by fehrenbach** [comment]
No idea what's happening here. I tried to disable caching in #237. Didn't help.

**Comment by dhil** [comment]
I opened an issue about this on the GutHub repository, c.f. https://github.com/mmottl/postgresql-ocaml/issues/21

**Comment by dhil** [comment]
I suggest we merge this patch now, and remove it once a fix emerges.

**Comment by fehrenbach** [comment]
```
[WARNING] At ~/.opam/4.04.0/packages.dev/links-dev/opam:73:9:
          Version constraint (<= 4.0.1) no longer allowed in optional
          dependency (ignored).
          Use the 'conflicts' field instead.
```
It doesn't do what we want. We could merge it anyway for "documentation".

**Comment by jamescheney** [comment]
Tried using the "conflicts" field and that "worked" (opam downgraded to postgresql 3.2.1, not 4.0.1).

4.1 seems to have started using jbuilder, so presumably there's something weird about its build process now.

**Pull request merged**
