### PR TITLE
Rename links-mysql8 driver to links-mysql

### PR DESCRIPTION
**Pull request by frank-emrich**
This PR renames  the `links-mysql8` driver to `links-mysql`. 

The idea is that for end users who upgrade from Links 0.9.7 to 0.9.8, the composition of #1178 (which removed the existing `links-mysql` driver) and this one has the effect of the `links-mysql` driver changing from using the `mysql8` package under the hood in the future, with no further changes from users required.

### CODE REVIEW

**Comment by frank-emrich** [comment]
This resolves #1182

**Comment by frank-emrich** [comment]
Note that parts of the CI now state "Waiting for status to be reported". That's because I've renamed some of the CI steps, all tests are actually passing as intended. Once this PR lands I will perform the same renaming on which CI steps Github expects to have passed.

**Comment by dhil** [comment]
> Note that parts of the CI now state "Waiting for status to be reported". That's because I've renamed some of the CI steps, all tests are actually passing as intended. Once this PR lands I will perform the same renaming on which CI steps Github expects to have passed.

Just delete the stale steps in the settings.

**Review by jamescheney — CHANGES_REQUESTED** [review]
This looks fine generally, I have a couple of  minor questions.

1.  Looking at tests/database, there are currently two (identical) files `factorials.mysql8` and `factorials.mysql`, containing MySQL-specific SQL code to initialize the database for the test `factorials.links`.  My guess is that after making this change, only the `factorials.mysql` file will ever be used by the test scripts, so the `factorials.mysql8` file can be deleted.

2.  Looking at the changes to tests/relational-lenses, I was initially surprised to see that `config.mysql8` is deleted and no `config.mysql` is created.  The reason seems to be that `config.mysql` exists and has the correct contents already, presumably because it was not deleted earlier.  So that's fine.  However, looking at the rest of this directory, it appears that there are again identical files `serial.mysql` and `serial.mysql8` containing MySQL-specific database setup code where the second one will be dead code after this cange and so can be deleted now.

I mark "request changes" now because these bits of cleanup should probably happen now.

**Comment by frank-emrich** [comment]
Thanks, those file were indeed meant to be deleted, good catch!

**Review by jamescheney — APPROVED** [review]

**Comment by jamescheney** [comment]
Sorry, I didn't realize this was still waiting on me, LGTM.

**Pull request merged**
