### PR TITLE
Add a simple links-mode for Emacs

### PR DESCRIPTION
**Pull request by jstolarek**
Because I was bored. Supports:

  * highlighting of keywords, primitive types, builtins and comments
  * commenting/uncommenting using `M-;`

Nothing fancy. Install by putting `links-mode.el` where Emacs can find it and adding `(require 'links-mode)` to your `.emacs` file.

### CODE REVIEW

**Comment by fehrenbach** [comment]
You might want to merge this in with https://github.com/links-lang/links/blob/master/links-mode.el

**Comment by jstolarek** [comment]
Good point. Done now. So this essentially ads highlighting builtin primitive types and functions.

**Comment by fehrenbach** [comment]
Is highlighting of built-in functions something people actually want? I always find it irritating when functions look differently just because they are built-in/have been defined in the prelude. Maybe some magical ones, like `sysexit`, but `take` and `drop`? (And *not* `map`, by the way.)

But then again, I'm not exactly an active Links user these days, so my opinion should probably not count for very much :)

**Comment by dhil** [comment]
How does the highlighting of primitives interact with shadowing? 

As outlined in #468 I would like to hoist some of the primitives out of the compiler, and implement them using Links. At that stage, they may well cease to be considered as primitives.

**Comment by jstolarek** [comment]
As you can see the list of builtins is currently hard-coded, so it changes we would need to update it.

> I always find it irritating when functions look differently just because they are built-in/have been defined in the prelude.

So I wonder what others think. I personally find highlighting of builtins helpful but that might be because I'm less experienced in Links and don't know all of them by heart.

**Comment by dhil** [comment]
> As you can see the list of builtins is currently hard-coded, so it changes we would need to update it.

I understand that as it would interact badly with shadowing of primitives, e.g.
```links
fun error(x) { x + 1 }
fun main() {
  error(2)
}
```
then `error` would be wrongly highlighted as a primitive function.

**Comment by jstolarek** [comment]
Yes, that's correct.

**Comment by dhil** [comment]
> Yes, that's correct.

OK. Thanks. Then I will object to merging this into `links-mode.el`.

**Comment by jstolarek** [comment]
I agree, this is a flaw I haven't thought about.

That leaves us with highlighting of primitive types (Int, Char, etc.). Is that an acceptable addition? If so I will update the PR.

**Comment by fehrenbach** [comment]
Can Emacs "faces" inherit from each other? We could create a new built-in-function face that inherits from whatever the default face is. This way, people who want to highlight built-ins can just customize the appropriate face and others will never know the difference.

**Comment by dhil** [comment]
Well, as discussed in #455 the intended semantics is to support shadowing of types, I don't know whether the intention is to cover primitive types too. The current implementation does not support this properly (that is evident from looking at how `parser.mly` handles data types declarations).
```links
links> typename Bool = Int;
Bool = Int
links> sig f : (Bool) -> Bool fun f(x) { x };
f = fun : (Bool) -> Bool
links> f(2);
<stdin>:1: Type error: The function
    `f'
has type
    `(Bool) -a-> Bool'
while the arguments passed to it have types
    `Int'
and the currently allowed effects are
    `wild'
In expression: f(2).
```

**Comment by fehrenbach** [comment]
Somewhat inconsistently I like highlighted primitive types. (Because I can never remember whether any particular given language spells it Bool or Boolean...)

**Comment by jstolarek** [comment]
> Can Emacs "faces" inherit from each other?

An educated guess would be that this is possible, given how customizable Emacs is, but I'd have to spend some time to go through Emacs documentation to figure out how to do it.

**Comment by jstolarek** [comment]
I'm sending this PR down the drain. The already existing links-mode does the most important thing that I need (block commenting/uncommenting) and the changes this PR introduces are controversial.

**Pull request closed without merging**
