### PR TITLE
Handlers for Algebraic Effects in Links

### LINKED ISSUE #192: Effect handlers extension

### PR DESCRIPTION
**Pull request by dhil**
This PR adds algebraic effects and handlers as a togglable extension to Links.

In principle it could be merged now. But I would like to do a few more tweaks before merging it. Also,  I'd like to document the major changes to the Links compiler infrastructure before anyone attempts to review this PR.

TODO:

* [x] ~Improve error messages~
* [x] ~Document server-side continuation structure~
* [x] ~Document client-side continuation structure~
* [x] ~Tidy up `examples/handlers/` directory~

Resolves  #192.

### CODE REVIEW

**Comment by SimonJF** [comment]
Congrats, @dhil! Looking forward to this being in the main branch :) Let us know when it's ready for reviewing!

(Also, +21k / -1.2k LoC -- wow, that's quite some work!)

**Comment by dhil** [comment]
As we agreed, I will silently commit my cosmetic changes later. This PR is ready to be merged.

**Comment by dhil** [comment]
I will squash-and-merge this on Friday, unless there are any objections.

**Comment by dhil** [comment]
Since nobody objected, I shall go ahead and merge in T - 60 seconds.

**Comment by SimonJF** [comment]
Congratulations, Daniel!
________________________________

**Pull request merged**
