### PR TITLE
Fix crop example

### PR DESCRIPTION
**Pull request by SimonJF**
Fix draggable handles example.

It was nothing insidious (although took a bit of debugging): turns out we just needed to have `px` added when setting the styles. My guess is that the behaviour was removed from modern browsers, or this was a result of adding in the `<!doctype html>` tag.

### CODE REVIEW

**Comment by SimonJF** [comment]
Fixes #578 .

**Comment by slindley** [comment]
Ah. Good. There appears to still be a bug - but maybe it was always there. The initial display doesn't show the view inside the initial cropping box but rather the entire image. It only does the right thing when we drag one of the corners for the first time.

**Comment by SimonJF** [comment]
Good spot - it was the same issue, just in static HTML.

**Comment by slindley** [comment]
That's better, but it's still not right. The initial view is of the top-left corner, but the cropping frame is not placed there.

**Comment by SimonJF** [comment]
I have no idea why this has brought 52 files' worth of diff in -- but I'll close and open another PR.

**Pull request closed without merging**
