### PR TITLE
Automatic source rule checking

### LINKED ISSUE #396: Require pull requests to rebase on top of master prior to being merged
We use the squash'n'merge strategy for merging in pull requests on the master branch. This is good, because it allows us to develop our changes incrementally in many small commits that not necessarily meaningful on their own, but when merged they get squashed into one big meaningful commit.

There is however a "hygiene problem" with the squash'n'merge strategy as it makes possible to re-merge changes that are already present in the master branch. This is for example happening in #385 PR which merges some +5000 changes of which several hundreds are redundant (I don't have anything against this particular PR being merged as-is; it just reminded me of the problem).

The redundancy does not cause any harm to the master branch per see, but it does have irksome side-effects such as increasing the likelihood of merge-conflicts and obfuscating the commit history. 

For example, say that branch A introduces a redundant commit into the master branch and B is another active branch. Suppose that B was recently rebased on top of the master branch during which some merge conflicts were resolved. Merging A into master may reintroduce the merge conflicts next time B rebases on top of master. 

Moreover, the author of the redundant commit gets credited for the work, meaning that -- as far as git is concerned -- the author takes ownership of the code. This can prove to be problematic when trying to nail down who-wrote-what.

Thus I suggest that we require as a minimum that every pull request must be able to be rebased on the master branch before it is merged in. I reckon we can even instrument the continuous integration tool to check this invariant. Adding something along the lines of the following command to the `script` section in the Travis configuration file ought to work.
```
script:
- git fetch && git rebase origin/master
```

In summary: I propose we continue to use squash'n'merge as our primary strategy, but we require that any pull request is at least able to rebase on top of the current master as well.

### PR DESCRIPTION
**Pull request by dhil**
Instruct Travis to perform some simple source rule checks.

This PR is dog-fooding itself.

Closes #396.

### CODE REVIEW

**Comment by frank-emrich** [comment]
We may consider adding validate_typecheck_testfile.testscript to the rules being checked, as opposed to being part of the test suite.

One thing that seems problematic is that this only checks that a PR is rebased on master at the time of creating the PR. However, it does not catch the case that master moves forward during the lifetime of the PR.

**Comment by frank-emrich** [comment]
I have just discovered the "protected branches" feature of github. One of its settings allows to enforce that PRs can only be merged if they are rebased on top of the current master already AND the checks (e.g., Travis) have run in that configuration (i.e., on top of the curren master).

https://help.github.com/enterprise/2.14/admin/guides/developer-workflow/configuring-protected-branches-and-required-status-checks/

**Comment by dhil** [comment]
@frank-emrich yes you are right this automatically account for the case when the master moves ahead of the PR. Interesting, I was not aware of protected branches, I wonder whether they are available outside of the enterprise edition.

Good point regarding the test script.

**Comment by dhil** [comment]
Brilliant! The PR failed due to trailing white space..

**Comment by frank-emrich** [comment]
I have now made Links' master branch protected such that it requires Travis to have finished before merging and the PR must be based on the current master in order to do so. There is an override, for people who are adminstrators of the Links project (which seems to be everyone actually working on it).

**Comment by dhil** [comment]
@frank-emrich thank you!

**Pull request merged**
