### PR TITLE
Add loading spinner to examples page

### PR DESCRIPTION
**Pull request by elordin**
Now with the Links-logo as spinner

### CODE REVIEW

**Comment by elordin** [comment]
Goddammit cross-browser-compatibility *shakes fist angrily*

**Comment by dhil** [comment]
It bounces no more in Firefox. Thanks.

Any chance of making the background white? I suppose the colours of the spinner will have to be changed slightly in order to render properly on a white background.

**Comment by dhil** [comment]
I love it.

I would like to have the text "Loading example..." right of the spinner.

**Comment by dhil** [comment]
Great! Thank you for adding the text.

I think this spinner is my favourite thing about Links now.

**Pull request merged**
