### PR TITLE
Initial stab at #841 for discussion

### PR DESCRIPTION
**Pull request by jamescheney**
This PR shows what happens if we make the use of `asList` and table comprehensions (`for (..<--..)`) stricter as proposed in #841.  This bakes good style into the type system, so that queries now always happen only when the `query` keyword appears.

The type system is still somewhat relaxed about allowing `query` to appear nested inside another `query`, and `query` keywords can also not result in queries being issued if the contents don't actually refer to a database table.  On the other hand, `query nested`s can generate several SQL queries.  So the correspondence is not 1-1.  But I still think this is an improvement.

To do:
- [x] Discussion whether this is reasonable / assess impact on other code
- [x] Remove commented code
- [x] Remove `wrapTableIterators` module

### CODE REVIEW

**Comment by jamescheney** [comment]
@SimonJF could you have a look to see how painful this is to accommodate in GtoPdb?

@slindley I've come to the conculsion that #838 was an unsustainable half measure.  So I'd rather either do this or leave as is (i.e. keep the inconsistent treatment of `<--` and allow use of `asList` if we really want to work with intermediate nested structure.)

**Comment by slindley** [comment]
@jamescheney I agree.

I'm happy to either stick with the current elaboration or to change the behaviour of `<--` to not insert a query providing we're stricter about the effect typing on `<--` and `asList` in order to prevent accidentally loading in whole tables.

The intermediate half-measure is not viable.

On balance, I think I am persuaded that thinking about where queries happen is important enough that it is a good idea to insist that the programmer always makes this explicit - so we should enact #841 and strive to avoid implicitly including `query` in any syntactic sugar.

**Comment by jamescheney** [comment]
OK, sounds good.  As we (hopefully) further extend the query capabilities I think being explicit about where queries may / cannot happen will help.  Can you / @SimonJF have a look to see if there are any unintended consequences on the tests or GtoPdb?

**Comment by SimonJF** [comment]
Sorry, missed this. Will have a look wrt. GtoPdb now.

**Comment by SimonJF** [comment]
This seems too restrictive at present. Take the following for example:

```
var furtherReading =
          for (fr <-- Tables.grac_further_reading)
            where (fr.family_id == familyId)
            for (ref <-- Tables.reference)
              where (ref.reference_id == fr.reference_id)
              [
                (makeReference(ref.reference_id,
                   ref.type, ref.title, ref.article_title, ref.year,
                   ref.volume, ref.issue, ref.pages, ref.publisher,
                   ref.publisher_address, ref.editors, ref.pubmed_id,
                   ref.isbn, ref.authors, fr.key_ref))
              ];
        var furtherReading =
          sortBy(fun(ref) { ref.authors }, furtherReading);
```

This is an "in the wild" instance of a "bare" `<--`. Adding the `query` block gets me:

```
        var furtherReading =
          query {
            for (fr <-- Tables.grac_further_reading)
              where (fr.family_id == familyId)
              for (ref <-- Tables.reference)
                where (ref.reference_id == fr.reference_id)
                [
                  (makeReference(ref.reference_id,
                     ref.type, ref.title, ref.article_title, ref.year,
                     ref.volume, ref.issue, ref.pages, ref.publisher,
                     ref.publisher_address, ref.editors, ref.pubmed_id,
                     ref.isbn, ref.authors, fr.key_ref))
                ]
          };
        var furtherReading =
          sortBy(fun(ref) { ref.authors }, furtherReading);
```

However, I still get an error:

```
[simon@dazzle skye-gtopdb]$ ./run.sh 
Unification error: Rows
 
and
 wild|_
 could not be unified because the former is rigid and the latter contains fields not present in the former, namely `wild'.
src/web/familyDisplay.links:430: Type error: The function
    `sortBy'
has type
    `(((...)) ~a~> String, [(...)]) ~a~> [(...)]'
while the arguments passed to it have types
    `((...)) ~a~> String'
and
    `[(...)]'
and the currently allowed effects are
    `'
In expression: sortBy(fun(ref) { ref.authors }, furtherReading).
```

**Comment by jamescheney** [comment]
That's strange.  Are you sure the reason for the error is not the earlier unguarded `for` expression:
```
var basicInfo =
      for (f <-- Tables.family)
        where (f.family_id == familyId)
        [(name = f.name, type = f.type,
            grac_texts =
              for (g <-- Tables.grac_family_text)
                where (g.family_id == familyId)
                [g])];
```
which will force the whole function body to be tame?

**Comment by jamescheney** [comment]
(or the other later unguarded queries `subcommitteeMembers` and `additionalContributors`)?

**Comment by SimonJF** [comment]
Ah, of course! Thanks for pointing that out -- I'd missed it.

The actual edits I needed to make to GtoPdb were minimal. I was taking advantage of the automatic insertion in places, but nothing really changed modulo a few query blocks being added (you can see the diffs in the repository).

So I'd be happy with this.

**Comment by jamescheney** [comment]
OK. Sam seems happy also so will merge after #852.

**Comment by jamescheney** [comment]
Obviously the error message could be more helpful when this happens also...

**Pull request merged**
