### PR TITLE
Quantified instantiation disabled by default

### PR DESCRIPTION
**Pull request by frank-emrich**
This is the result of some intense hacking with Sam.

Two bugs are fixed, and quantified_instantiation is enabled for those tests that actually need it.

### CODE REVIEW

**Comment by jstolarek** [comment]
It is nice to see this! I was about to ask about progress on this one.

Do I take it that we ignore problems with the IR typing in the presence of `quantified_instantiation` and just try to eliminate bugs that are present when `quantified_instantiation` is disabled? (At least for now.)

**Comment by jstolarek** [comment]
I would be happy to see this merged.

@slindley, what is the status of your `ordered-quantification` branch? Will it be getting into merge-ready state any time soon? I am preparing to rebase and fix #534 and I'd like to do it on top of latest typechecking bugfixes.

**Comment by jamescheney** [comment]
@slindley, could you take a quick look?

**Comment by jamescheney** [comment]
Oops, never mind, wrong issue!

**Pull request merged**
