### PR TITLE
Cohttp_lwt_body --> Cohttp_lwt.Body

### PR DESCRIPTION
**Pull request by SimonJF**
Should fix CI?

### CODE REVIEW

**Comment by fehrenbach** [comment]
I'm still confused by the pp, it says 
```
ocamlc core/webserver.{cmo,cmt} (exit 2)
```
but reports the error as coming from core/webserver.pp.ml

But otherwise it looks like it compiles core/debug without problems and before it errors.

I'm out of ideas.

**Comment by fehrenbach** [comment]
Eh? So the error message for ambiguity in an unrelated module is "Debug.print is not a value"? Is that something one is expected to know? WTF?! Does Lwt or something have a nested Debug module that one of the `open`s brings into scope and we end up looking up stuff in there instead of our global Debug module?

**Comment by fehrenbach** [comment]
Actually, the last almost makes sense, but no warning? WTF?

**Comment by SimonJF** [comment]
Yeah, bloody bonkers isn't it. Ah well. Everything's working again now!

This should mean that I FINALLY make the release tomorrow morning -- squashing and merging for now though.

**Pull request merged**
