### PR TITLE
Adding my demo projects to the example folder

### PR DESCRIPTION
**Pull request by Corneliusbusch**

### CODE REVIEW

**Comment by jamescheney** [comment]
Is there anything holding up merging these?  Or do they belong in links-examples?

**Comment by dhil** [comment]
I think we agreed during the previous meeting that they belong to links-examples.

**Comment by slindley** [comment]
I think we did suggest putting them in links-examples initially, but then I suggested to Nicole that we just put them in the main repository instead, as they are all quite small, and some of them (certainly some of the handler examples) would be really good to have there. I'd be inclined to accept the pull request without many changes, but afterwards it might be worth doing some curation.

If others would prefer to use links-examples as a staging post, then that's also fine - as long as someone is happy to do that.

**Comment by dhil** [comment]
OK. I have no problem with putting them into this repository. I'll merge.

**Pull request merged**
