### PR TITLE
Removes the `dumpTypes` function from the Links standard library.

### PR DESCRIPTION
**Pull request by dhil**
This patch removes the built-in function `dumpTypes`. Judging from the
comment in `dumpTypes.ml` it seems that its sole purpose was to
provide some interface for displaying type information in an IDE. The
comment even states that it is a hack. Hack or not, the function does
not work any longer as it triggers an internal failure on use. My
guess is that this has been the case for a while.

I would like to remove this function as it specifically requires
access to the `prelude` typing environment. Access was provided via a
global hack which is at odds with how I would like to structure the
new modular loader (c.f. #603).

If we want to provide support for any kind of inspection, then I
firmly believe we should do the proper thing and generate object files
with adequate meta information.

### CODE REVIEW

**Comment by frank-emrich** [comment]
I'm always in favour of removing unused, unmaintained code :)

**Comment by slindley** [comment]
This was far too fast. It's probably fine to remove this code in this case, but in future please don't do the "oh I don't know what this is, it doesn't seem to be needed, I'll just delete it" thing without asking me first. I believe this was used by an undergraduate student of mine about 11 or 12 years ago for a project in which he wrote a nice web-based IDE for Links:

  http://links-lang.org/papers/undergrads/tom.pdf

We don't have a working version of Tom's IDE, though perhaps this kind of functionality could be useful in future - e.g. for an improved emacs mode.

Next time someone does this, I will revert pending a proper chance to assess what is actually being deleted.

**Comment by jamescheney** [comment]
Sorry, I was aware that this was used in a project, but didn't mention it (I became confused as to which project, since I wasn't applying the rewrite "Carl" -> "Tom").  It looks like the code for LODE still exists in branch `tom`, where `dumpTypes` still exists, and if we want to resurrect it then the branch is still there.

In any case, seems like this should have been an issue for discussion before taking action.

**Comment by slindley** [comment]
Yeah - it should have been an issue for discussion before taking action.

**Comment by dhil** [comment]
> This was far too fast. It's probably fine to remove this code in this case, but in future please don't do the "oh I don't know what this is, it doesn't seem to be needed, I'll just delete it" thing without asking **me** first.

I disagree. If nobody is willing to fix the broken code, then the right thing to do is to just get rid of it. We should not collect a insurmountable broken code base. I don't think it is feasible to have you assess every decision before it is made. Instead we should make much more use of the power of revision control, you even say it yourself

> Next time someone does this, I will revert pending a proper chance to assess what is actually being deleted.

We can just restore it again, no harm done.

I don't believe in the argument that we should keep a feature around because it was part of a project/phd/master/undergraduate thesis. It is definitely nice to be able to read the project/thesis and then run the code in Links. However, the right thing to do is to **tag** the master branch whenever a project or thesis is completed. That way one can always restore the exact state from the time of the project. We should be much happier getting rid of code that nobody wants to maintain.

**Comment by slindley** [comment]
You're missing the point. It should be established what is being removed before removing it. Absolutely, we can and should remove code that is no longer of interest. The problem is that recently people have been a bit too gung-ho about removing features they don't understand without proper discussion. In this case the pull-request you created was fine, but it should not have been approved without discussing with me or someone else who was familiar with the feature first.

**Comment by SimonJF** [comment]
Holding my hand up here: I was too keen with the merge button. My reasoning is that it seemed like an "obvious" win: the code was a hack (and stated as much); it was only used by ancient code that's no longer around; there was general consensus on the PR that removing it was a good idea; and it was actively blocking a new feature.

That said, it highlights a weakness in our previous process. Lessons learnt -- let's make sure we get that right going forward.

**Pull request merged**
