### PR TITLE
disable mac os azure CI for now

### LINKED ISSUE #792: Azure Mac CI breaks during database setup
This [build](https://dev.azure.com/links-lang/links/_build/results?buildId=621) failed repeatedly with the following error. Those changes are unrelated to DB-stuff; I guess master would equally fail.

```
cmnd=psql -h localhost -p 5432 -v ON_ERROR_STOP=1 -q -d links -f tests/shredding/travel_portal.sql
psql:tests/shredding/travel_portal.sql:1: NOTICE:  table "agencies" does not exist, skipping
psql:tests/shredding/travel_portal.sql:2: NOTICE:  table "externaltours" does not exist, skipping
psql:tests/shredding/travel_portal.sql:9: ERROR:  syntax error at or near "OIDS"
LINE 6: ) WITH OIDS;
               ^
```

Maybe the mac setup uses a new version of postgres that's not compatible with our script anymore?

### PR DESCRIPTION
**Pull request by jamescheney**
this is to see what the CI does, don't merge

### CODE REVIEW

**Comment by frank-emrich** [comment]
You say "don't merge" but I guess that's what we want to do for now?

**Comment by jamescheney** [comment]
I wasn't expressing a preference.  Over in #792 @dhil says he wants to keep the MacOS CI going.  I don't see how to do this easily given the version skew between Linux and Mac OS package managers at the moment. The right thing to do until the version skew disappears is probably to pin the version of Postgres that Brew installs, and then use an absolute path (or create appropriate symlinks) for `pg_ctl` and friends.  But I have no easy way of working out how to do this - I use a different package manager (and don't want to install brew just to play with it!)

**Comment by frank-emrich** [comment]
I've made my own (unsuccessfull) attempt at this; debugging it without having a working brew setup seems difficult. I suggest that until someone wants to invest the time of fiddling with this we go through with this PR and disable the Mac pipeline for now.

**Comment by dhil** [comment]
> I wasn't expressing a preference. Over in #792 @dhil says he wants to keep the MacOS CI going. I don't see how to do this easily given the version skew between Linux and Mac OS package managers at the moment. The right thing to do until the version skew disappears is probably to pin the version of Postgres that Brew installs, and then use an absolute path (or create appropriate symlinks) for `pg_ctl` and friends. But I have no easy way of working out how to do this - I use a different package manager (and don't want to install brew just to play with it!)

I don't think I said I wanted to keep it going, only that I am the defacto maintainer. I think it is fine to disable it. If you read issue #584 you will see that most of the issue has to do with the macOS image. I think `brew` may be the issue. However, I am not familiar with macOS package managers, I just followed a guide for configuring macOS when I made that image.

**Comment by dhil** [comment]
In fact I am happy to abandon the "abandon travis in favour of azure pipelines" attempt.

**Comment by dhil** [comment]
> [...] don't merge

Given the discussion in #584 and #792, I will elect to ignore this, and just merge the patch.

**Pull request merged**
