### PR TITLE
Properly escape carriage returns.

### PR DESCRIPTION
**Pull request by SimonJF**
Before, carriage returns weren't escaped (and the escaping code wasn't extensible). Now, there's a slightly nicer way of doing substitutions, and carriage returns are handled properly.

### CODE REVIEW

**Comment by dhil** [comment]
What about using [`Str.quote`](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Str.html) instead?

**Comment by SimonJF** [comment]
Thanks! Good idea, but it doesn't quite work:
```
# Str.global_replace (Str.regexp "'") (String.escaped "'") "'Hello', World";;
- : string = "'Hello', World"
```

**Comment by SimonJF** [comment]
That said, maybe `Str.escaped` on the whole string, and a substitution for quotes might be the best idea.

**Comment by SimonJF** [comment]
Much nicer, thanks for the suggestion!

**Pull request merged**
