### PR TITLE
rearranged makefiles to allow unit tests and added a small unit test

### PR DESCRIPTION
**Pull request by rudihorn**
Split Makefile into Makefile, MakefileLinksBase and MakefileLinksTests

This allows links to be compiled as usual with "make", but by using "make -f MakefileLinksTests" a linksTests binary is created that executes unit tests.

An example unit test is in unitTestsJson.ml

To simplify the execution of unit tests a script "run-unit-tests" was created, which runs the makefile and on successful compilation executes the tests and deletes the test binary afterwards.

This also includes some updates to .gitignore for temporary vim files and some further ocaml temporary files, as well as temporary oUnit files.

### CODE REVIEW

**Comment by dhil** [comment]
I thought the following might be of interest. I have previously handcrafted a makefile for Links which with a few additions compiles the master branch:
```Makefile
# Compilers
OCAMLC=ocamlc
CFLAGS=-annot -bin-annot -w Ae-44-45-60 -g -cclib -lunix -syntax camlp4o -thread
OCAMLOPT=ocamlopt
OPTFLAGS:=${CFLAGS}

# Parser generator
YACC=ocamlyacc
YACCFLAGS=-v
# Lexer generator
LEX=ocamllex
LEXFLAGS=

# Packages
PACKS=str \
      deriving.syntax deriving.syntax.classes deriving.runtime \
      lwt lwt.syntax lwt.unix \
      cgi cohttp cohttp.lwt \
      base64 unix \
      threads

# Comma separate the package list
comma:= ,
empty:=
space:= ${empty} ${empty}
PKGS:= ${subst ${space},${comma},${PACKS}}

# Other people's code.
OPC= unionfind.mli unionfind.ml \
     getopt.ml getopt.mli PP.ml

# Source files
SOURCES:= $(OPC)                                \
          multipart.ml                          \
          notfound.ml                           \
          utility.ml                            \
          processTypes.mli processTypes.ml      \
          env.mli env.ml                        \
          settings.mli settings.ml              \
          basicsettings.ml                      \
          debug.mli debug.ml                    \
          performance.mli performance.ml        \
          graph.ml                              \
          types.mli types.ml                    \
          constant.ml                           \
          sourceCode.ml                         \
          regex.ml                              \
          sugartypes.ml                         \
          parser.ml                            \
          lexer.mli lexer.ml                   \
          typeUtils.mli typeUtils.ml            \
          errors.mli errors.ml                  \
          instantiate.mli instantiate.ml        \
          generalise.mli generalise.ml          \
          typevarcheck.mli typevarcheck.ml      \
          unify.mli unify.ml                    \
          var.ml                                \
          ir.mli ir.ml                          \
          tables.ml                             \
          closures.ml                           \
          parse.mli parse.ml                    \
          sugarTraversals.mli  sugarTraversals.ml       \
	  moduleUtils.mli moduleUtils.ml \
          resolvePositions.mli resolvePositions.ml       \
	  chaser.mli chaser.ml \
	  desugarModules.mli desugarModules.ml \
          desugarDatatypes.mli desugarDatatypes.ml      \
          defaultAliases.ml                     \
	  requestData.mli requestData.ml        \
          value.mli value.ml                    \
          eventHandlers.mli eventHandlers.ml    \
          xmlParser.ml xmlLexer.ml            \
          parseXml.mli parseXml.ml              \
          refineBindings.mli refineBindings.ml           \
          desugarLAttributes.mli desugarLAttributes.ml   \
          transformSugar.mli transformSugar.ml           \
          fixTypeAbstractions.mli fixTypeAbstractions.ml \
          desugarPages.mli desugarPages.ml               \
          desugarFormlets.mli desugarFormlets.ml         \
          desugarRegexes.mli desugarRegexes.ml           \
          desugarFors.mli desugarFors.ml                 \
          desugarDbs.mli desugarDbs.ml                   \
          desugarFuns.mli desugarFuns.ml                 \
          desugarProcesses.mli desugarProcesses.ml       \
          desugarInners.mli desugarInners.ml             \
	  desugarCP.mli desugarCP.ml                     \
          typeSugar.mli typeSugar.ml                     \
          checkXmlQuasiquotes.ml                \
          frontend.ml                           \
          dumpTypes.ml                          \
          compilePatterns.ml                    \
          jsonparse.ml                         \
          jsonlex.ml                          \
          js.ml                                 \
          json.mli json.ml                      \
          proc.mli proc.ml                      \
	  resolveJsonState.mli resolveJsonState.ml \
          database.mli database.ml              \
          linksregex.ml                         \
	  lib.mli lib.ml                        \
          sugartoir.mli sugartoir.ml            \
          loader.mli loader.ml                  \
          irtojs.mli irtojs.ml                  \
          query.mli query.ml                    \
          queryshredding.ml                     \
          webserver_types.mli webserver_types.ml \
          webserver.mli                         \
	  evalir.ml                             \
          buildTables.ml                        \
          webif.mli webif.ml                    \
	  webserver.ml                          \
          links.ml                              \

# Object files
BYTE_OBJECTS=$(SOURCES:%.ml=%.cmo)
OPT_OBJECTS=$(SOURCES:%.ml=%.cmx)

# Target
RESULT=links

default: native

nc: native

native: ${OPT_OBJECTS}
	ocamlfind ${OCAMLOPT} ${OPTFLAGS} -o ${RESULT}.native \
                                          -linkpkg \
                                          -package ${PKGS} \
                                          ${OPT_OBJECTS}

byte: ${BYTE_OBJECTS}
	ocamlfind ${OCAMLC} ${CFLAGS} -o ${RESULT}.byte \
                                         -linkpkg \
                                         -package ${PKGS} \
                                         ${BYTE_OBJECTS}
%.ml %.mli: %.mly
	${YACC} ${YACCFLAGS} $*.mly

%.ml: %.mll
	${LEX} ${LEXFLAGS} $*.mll

%.cmo %.cmi: %.mli %.ml
	ocamlfind ${OCAMLC} ${CFLAGS} -package ${PKGS} $*.mli -c $*.ml

%.cmo: %.ml
	ocamlfind ${OCAMLC} ${CFLAGS} -package ${PKGS} -c $@ $<

%.cmx %.cmi: %.mli %.ml
	ocamlfind ${OCAMLOPT} ${OPTFLAGS} -package ${PKGS} $*.mli -c $*.ml

%.cmx: %.ml
	ocamlfind ${OCAMLOPT} ${OPTFLAGS} -package ${PKGS} -c $@ $<

test:
	echo "Rule not yet configured."

top: ${BYTE_OBJECTS}
	ocamlfind ocamlmktop ${CFLAGS} -o ${RESULT}.top \
	                        -linkpkg \
                                -package ${PKGS} \
                                ${BYTE_OBJECTS}

clean:
	rm -f *.cm* *.annot *.o
	rm -f parser.{ml,mli} lexer.ml xmlParser.{ml,mli} xmlLexer.ml
	rm -f *.output
	rm -f ${RESULT}.byte ${RESULT}.native ${RESULT}.top
```
This makefile does not link database bindings, though, that ought to be easy to fix. It is marginally slower than the current makefile with `OCamlMakefile`. I suspect this can be improved by using `ocamldep` to generate dependencies.

Using this makefile it would be straightforward to define multiple compilation targets.

**Comment by jamescheney** [comment]
Or, we could use OMake, which is happy to generate multiple executables (as well as handle files in different subdirectories, build libraries, deal with lex/yacc etc.).  See for example:

https://github.com/links-lang/links/tree/jrc-omake-test2
https://github.com/links-lang/links/blob/jrc-omake-test2/OMakefile

to run this, you need omake installed, which is available from OPAM; you then just need to type "omake" instead of "make".  Adding a different target should just be a matter of adding a couple lines like so:

```
TEST_PROGRAM = unitTests
OCamlProgram( $(TEST_PROGRAM), $(FILES))
```

I'm half inclined to merge that; it doesn't do any harm, if some people want to stick with the existing OCamlMakefile for speed / official builds, while others use OMake to build tests.

**Comment by dhil** [comment]
Sounds good to me.

**Comment by rudihorn** [comment]
I saw the OCamlMakefile we currently use contains something about subprojects (http://mmottl.github.io/ocaml-makefile/) although it didn't look like the nicest thing to use. Probably better than reinventing the wheel and writing our own makefile though. I do like the omake idea though, but one would have to ensure that one isn't having to maintain multiple source code lists.

They seem to suggest a syntax for compiling a subproject as `%: @make -f $(OCAMLMAKEFILE) subprojs SUBTARGET=$@`

**Comment by dhil** [comment]
The subprojects approach would at least be uniform. It seems like a good option for now, if it is not too much trouble to configure. I am not particularly fond of OCamlMakefile; hopefully we can transition to a better build system in the future.

**Comment by jamescheney** [comment]
We discussed this and decided that James and Rudi need to coordinate to decide how to proceed (using OMake or what).

**Comment by rudihorn** [comment]
I have been experimenting with omake, and it seems to have some difficulties with having different packages for different compile targets.  This seems to be because it uses a global variable called OCAMLPACKS to store them, and make rules are essentially generated before executed (at least as far as I can understand). This would make it necessary to have oUnit as a dependency for regular compilations which I am not such a big fan of. Below is a simplified version of how it is possible to add an extra compile switch for unit tests, but that would require the default compilation strategy to include oUnit as a package. Any ideas?

`OCAMLPACKS = ... oUnit

FILES[] = ...
DEFAULT_FILES[] = 
   $(FILES)
   links
UNIT_FILES[] = 
   $(FILES)
   ...
   unitTests

DEFAULT_PROGRAM = links
UNIT_PROGRAM = links_unit

OCamlProgram( $(DEFAULT_PROGRAM), $(DEFAULT_FILES))
.DEFAULT: $(if $(BYTE_ENABLED), $(DEFAULT_PROGRAM).run) \
          $(if $(NATIVE_ENABLED), $(DEFAULT_PROGRAM).opt)

.PHONY: unit 
unit: $(OCamlProgram $(UNIT_PROGRAM), $(UNIT_FILES))`

**Comment by jamescheney** [comment]
I think this would be OK for now, given that the OMakefile is not replacing the standard Makefile which we will continue to use for building Links for normal development.

Conditionally including a library for a specific target should be possible using OMake.  Might be worth skimming through the OMake recipes, for example:
http://www.camlcity.org/knowledge/kb_001_omake_recipes.html#multi-programs

**Comment by jamescheney** [comment]
Oops, it looks like the link I gave above explicitly does not handle the case you want to handle (with target-dependent OCAMLPACKS.)  Instead look here:

http://www.camlcity.org/knowledge/kb_001_omake_recipes.html#deviating-flags

though this looks a little more painful.  An alternative may be to put the unit-testing stuff in a subdirectory with its own OMakefile and locally modify the OCAMLPACKS variable there...

**Comment by rudihorn** [comment]
I think having multiple build systems would not be a great solution though, and if multiple make files are necessary in any case then it would probably be best to stick to the solution proposed where it is possible to reuse common things from the main makefile as much as possible (or if omake is preferred to do the same type of thing with omake, potentially with a subdirectory which may be a nice idea).

**Comment by dhil** [comment]
> I think having multiple build systems would not be a great solution

Yes, we need to revisit #62 and #78 at some point. It would be good to settle on a better build system than the current one. JBuilder (c.f. https://github.com/janestreet/jbuilder) might pose an interesting alternative.

**Comment by jamescheney** [comment]
I think we agreed to revisit this just after the next release, along with #81. (and possibly consider other building options such as jbuilder.)

**Pull request closed without merging**
