### PR TITLE
Extend XML support; Clean up JS

### PR DESCRIPTION
**Pull request by elordin**
- [x] XML <-> Variant type conversions
- [x] Various XML util methods
- [x] Name-spaced XML (currently by variant-type only, not via manual input + parser)
- [x] Remove the YAHOO library
- [x] Some general clean up in `jslib`
- [x] Add strict mode in `jslib`
- [x] Update js compiler to use strict mode

### CODE REVIEW

**Comment by elordin** [comment]
Tested all (nodb) examples + chatserver. All work as intended.

**Comment by elordin** [comment]
CI fails with
```
!FAILURE: XML Construction
  error: XML Construction
      (Unexpected stdout: expected `<foo id="bar" class="baz"><div/></foo> : XmlItem'; got `<foo id="bar"class="baz"><div/></foo> : XmlItem')
```
(`/tests/xml.tests`)

Test-case is
```
XML Construction 
makeXml("foo", [ ("id", "bar"), ("class", "baz") ], <div/>)
stdout : <foo id="bar" class="baz"><div/></foo> : XmlItem  
```
which, when I execute it manually, produces the correct output.

Can someone else please double check this ?!

**Comment by fehrenbach** [comment]
That's probably my fault. I'll have a look.

**Comment by elordin** [comment]
Don't think it's your fault. 
The error also occurs when running the tests locally.
But somehow the space between attributes is only missing in this specific test-case and only when running as a test-case.
Other tests are fine and executing that code manually also produces the correct output.

**Comment by fehrenbach** [comment]
Okay, so this works on master.
In your branch it misses the space when `print_pretty` is set to true.

```
stefan@icarus:~/src/links xml-support$ ./links --config=pretty.config -e 'makeXml("foo", [ ("id", "bar"), ("class", "baz") ], <div/>)'
<foo id="bar" class="baz"><div/></foo> : XmlItem
stefan@icarus:~/src/links xml-support$ ./links --config=nopretty.config -e 'makeXml("foo", [ ("id", "bar"), ("class", "baz") ], <div/>)'<foo id="bar"class="baz"><div/></foo> : XmlItem
```

I don't have to time right now to dig through >6000 changed lines. If you still have a more fine-grained history around, you might want to try to bisect this.

There seems to be a newline missing, too. This suggests string_of_value is not working as intended. Another way is to force string_of_value use by using `show`:

```
stefan@icarus:~/src/links xml-support$ ./links --config=nopretty.config -e 'show(makeXml("foo", [ ("id", "bar"), ("class", "baz") ], <div/>))'
"<foo id="bar"class="baz"><div/></foo>" : String
stefan@icarus:~/src/links xml-support$ ./links --config=pretty.config -e 'show(makeXml("foo", [ ("id", "bar"), ("class", "baz") ], <div/>))'
"<foo id="bar"class="baz"><div/></foo>" : String
```

This also works in master, though...

**Comment by fehrenbach** [comment]
One idea: do you call string_of_value on `Attr`s and concatenate?

**Comment by dhil** [comment]
@elordin do the examples run with `enable_handlers = true`?

**Comment by jamescheney** [comment]
If you test locally, make sure you delete prelude.links.cache.  Otherwise,
Links might happily load the old version of the prelude and use the oldv
ersion of makeXml, shadowing the buggy version.

**Comment by jamescheney** [comment]
Hmm... seems to be a difference in how `XmlItem` vs. `Xml`s (== `[XmlItem]`s) are printed.

Also Links correctly parses XML without spaces between closing `"`s and the following attribute name.  Is that legal XML?

```
$ ./links -w
 _     _ __   _ _  __  ___
/ |   | |  \ | | |/ / / ._\
| |   | | , \| |   /  \  \
| |___| | |\ \ | |\ \ _\  \
|_____|_|_| \__|_| \_|____/
Welcome to Links version 0.7 (Dalry)
links> makeXml("foo", [ ("id", "bar"), ("class", "baz") ], <div/>);
<foo id="bar"class="baz"><div/></foo> : XmlItem

links> <foo id="bar"class="baz"><div/></foo>;
<foo id="bar" class="baz"><div/></foo> : Xml

links> [makeXml("foo", [ ("id", "bar"), ("class", "baz") ], <div/>)];
<foo id="bar" class="baz"><div/></foo> : [XmlItem]
```

**Comment by elordin** [comment]
> Also Links correctly parses XML without spaces between closing "s and the following attribute name. Is that legal XML?

No, it is not.

What exactly is the `-w` flag for? Since without it there is no missing space between attributes.

**Comment by jamescheney** [comment]
`-w` puts Links into web mode, which (along with some other complicated conditions) suffices to disable pretty-printing:

https://github.com/links-lang/links/blob/c6b76f55deb4110027dff837bf8a52c18e5002c2/links.ml#L18

**Comment by elordin** [comment]
Just checked on `master`. Same behaviour.

So I'll just add the test case with `ignore` for now and defer fixing that as a bug.

With that this PR is ready for merging.

**Comment by jamescheney** [comment]
The immediate reason for the regression is probably that changing the return type of `makeXml` from `Xml` (in prelude.links) to `XmlItem` (in lib.ml) unmasked a bug in XML pretty printing, but so far I can't see what the bug is.  Happy with merging.

**Comment by dhil** [comment]
Can you confirm that you have tested the web examples with `enable_handlers=true`?

**Comment by elordin** [comment]
> Web examples ~"chatserver" and~ "progress" are broken when enable_handlers=true.

FTFY. Progress-bar example works, chatserver still as broken as it is on `master`

**Comment by dhil** [comment]
@elordin please synchronise the branch `xml-support` with `master`. Then I will try some handlers examples with your changes.

**Comment by elordin** [comment]
Just for the record:
```
Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
```
has, in all cases that I have seen so far, been a `500 Internal Server` error. So there should be an error on the servers `stderr` (which is the jsonparse error in this case because I only updated the way XML is encoded in one direction, m.c.)

**Pull request merged**
