### PR TITLE
Enforce dummy positions inside compiler pipeline

### PR DESCRIPTION
**Pull request by jstolarek**
A simple fix for #460, hopefully uncontroversial.

### CODE REVIEW

**Comment by dhil** [comment]
I don't quite understand the rationale for #460. It seems to me that desugaring passes now suffer a loss of information.

**Comment by jstolarek** [comment]
The rationale is the same as for #423. Positions should correspond only to source code tokens and so it makes no sense to attach positions to AST nodes created inside the compiler pipeline. Such nodes have no corresponding source code tokens, even though they are derived from one, and so I argue that it makes no sense to propagate positions to these derived nodes. These shouldn't even be a problem. Positions should only be used for error reporting and we should catch errors before or during desugaring, not after (we shouldn't desugar incorrect programs). I realize that this last condition might not actually hold, i.e. we first desugar and then report errors, but if that is the case then I argue this is a Bad Thing (TM) and it should be fixed.

Note also that sugarTraversals maintain positions without changing them.

**Comment by dhil** [comment]
> Positions should only be used for error reporting and we should catch errors before or during desugaring, not after (we shouldn't desugar incorrect programs). I realize that this last condition might not actually hold, i.e. we first desugar and then report errors, but if that is the case then I argue this is a Bad Thing (TM) and it should be fixed.

Debugging Links programs is somewhat painful, I reckon taking away helpful information such as positions on desugared nodes will just make it even more painful to debug programs. Therefore I suggest we wait with merging this PR until the the invariant that you describe is true.

**Comment by jstolarek** [comment]
> I suggest we wait with merging this PR until the the invariant that you describe is true.

I believe it will be easier to reach that invariant by merging this PR first. Why? Firstly, I don't know whether this invariant is true or not at the moment. I would have to inspect a significant chunk of Links source code to see whether that's the case - and I still might make a mistake. Now, if me merge this PR and then if we manage to get an error message with a dummy position attached to it then that's a clear bug that points us to something that should be fixed. If we keep things as they are, even if we get error messages generated after desugaring, we might not realize that this is something that shouldn't happen. 

BTW. my changes didn't break any of the tests, so perhaps there is no situation at the moment where we are using this position information.

**Comment by jamescheney** [comment]
This is related to an earlier discussion somewhere about whether to generalize the type of "positions" to allow us to say "this ast node was created by desugaring pass XYZ using input ast nodes with the following "position" information" - where the position information of the previous ast nodes might be a plain source code location or another derivation step.  (I.e. a form of "how" provenance).  I think Janek's response to that was that we should not need that kind of information if everything works, i.e. in the end state mentioned above where everything that typechecks desugars properly.  I submit that since Links is a permanent work in progress, we will usually not be in that state and thus, at least optionally, maintaining more detailed information that might be helpful to get an idea of what went wrong might be a good idea.

**Comment by slindley** [comment]
I agree with @jamescheney. This is a controversial change that I suggest we discuss at the next Links developer meeting.

One problem that this issue highlights is that our test suite does not cover (and possibly cannot cover) much of the diagnostic information that we may need when developing Links. Given that Links is primarily a research vehicle, this might be something we want to think about addressing.

**Comment by jstolarek** [comment]
Ok, let's discuss this during the next dev meeting.

**Comment by jstolarek** [comment]
I updated this PR following yesterday's discussion during dev meeting. It fixes #460 and #480, and is rebased on top of polymorphic variants branch.

The important bit is that now there are two concrete implementations of `SugarConstructors` functor available: one that allows attaching standard sugartypes positions (this one is used to traverse the AST and leave the positions untouched, but also to propagate positions to derived nodes) and one that only allows to attach dummy positions. See Note [Attaching positions to nodes] in sugarConstructors.ml

**Pull request closed without merging**
