### PR TITLE
Simplify typeSugar

### PR DESCRIPTION
**Pull request by jstolarek**
Remove some duplicated logic. Instead of inlining pattern environment computation inside `type_pattern` just call already existing `pattern_env` after typing the pattern.

### CODE REVIEW

**Comment by slindley** [comment]
This is an unsound refactoring. The `pattern_env` function is only valid for let-patterns (not case-patterns) because it does not distinguish the inner and outer types. See the `Negative` and `As` cases of `type_pattern`. I'm a bit dismayed that our tests don't seem to detect the regression introduced here.

**Comment by jstolarek** [comment]
`Negative` cases actually seem identical - both return an empty environment. I agree about the difference in the `As` case though. I missed that one.

**Comment by slindley** [comment]
The `Negative` case is a source of different inner and outer types

    let outer_type = `Variant (positive, row_var, false) in
    let inner_type = `Variant (negative, row_var, false) in
    Negative names, Env.empty, (outer_type, inner_type)

as is the `HasType` case.

The `As` case puts the inner type into the environment.

**Comment by slindley** [comment]
Hmmm... looking more closely at this, I think this refactoring is correct after all! Environment bindings come from variables and `As` patterns. For the `Variable` case there is no difference between the inner and outer type. For `As` patterns `pattern_env` extracts the type from the binder, which is already annotated with the inner type as required.

**Comment by jstolarek** [comment]
Closed via b46003ebc7c44151b1a50120b7b2e0022c593260

**Pull request closed without merging**
